name: Test

on:
  push:
    branches: main
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - uv.lock
      - '**.py'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/uv.yml@0832d473774c1447617374fce8cf68e75c50dd7f # main
